language: r
cache: packages

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
