language: r
cache: packages

warnings_are_errors: false

env:
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

addons:
  apt:
    packages:
      - libgdal-dev
      - libudunits2-dev

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: change
